services:
  uets-server:
    environment:
      - PYTHONUNBUFFERED=1
    image: ghcr.io/nyxiereal/userfiles/uets-server:latest
    ports:
      - '5000:5000'
    volumes:
      - ./data:/app/data
    restart: unless-stopped